# Generated by Django 6.0.2 on 2026-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distillery', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('scotland', 'Scotland'), ('usa', 'USA'), ('ireland', 'Ireland'), ('japan', 'Japan'), ('canada', 'Canada'), ('taiwan', 'Taiwan'), ('india', 'India'), ('other', 'Other')], max_length=50)),
                ('whisky_type', models.CharField(choices=[('single_malt', 'Single Malt'), ('blended', 'Blended'), ('blended_malt', 'Blended Malt'), ('single_grain', 'Single Grain'), ('bourbon', 'Bourbon'), ('rye', 'Rye'), ('tennessee', 'Tennessee'), ('single_pot_still', 'Single Pot Still'), ('other', 'Other')], max_length=50)),
                ('region', models.CharField(blank=True, choices=[('islay', 'Islay'), ('speyside', 'Speyside'), ('highlands', 'Highlands'), ('lowlands', 'Lowlands'), ('campbeltown', 'Campbeltown'), ('islands', 'Islands'), ('kentucky', 'Kentucky'), ('tennessee', 'Tennessee'), ('other', 'Other')], max_length=50)),
                ('age', models.PositiveBigIntegerField(blank=True, null=True)),
                ('abv', models.FloatField()),
                ('peat_level', models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='none', max_length=10)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('bartender_tip', models.TextField(blank=True)),
                ('pairing', models.JSONField(blank=True, default=list)),
                ('serving_guide', models.JSONField(blank=True, default=dict)),
                ('flavor_profile', models.JSONField(blank=True, default=dict)),
                ('price_tier', models.CharField(blank=True, choices=[('budget', 'Budget (~₩50,000)'), ('mid', 'Mid-range (₩50,000~₩100,000)'), ('premium', 'Premium (₩100,000~₩200,000)'), ('luxury', 'Luxury (₩200,000~)')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='whiskies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cask_types', models.ManyToManyField(blank=True, to='whisky.casktype')),
            ],
        ),
    ]
