# Generated by Django 6.0.2 on 2026-03-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whisky', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('whisky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='whisky.whisky')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'whisky')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
                ('whisky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='whisky.whisky')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'whisky')},
            },
        ),
    ]
